name: Publish package to (Test-)PyPI

on:
  release:
    types: [published, prereleased]

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install wheel
        run: >-
          pip install wheel
      - name: Build
        run: >-
          python3 setup.py sdist bdist_wheel
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

